INSERT INTO tb_categories (name) VALUES
('Smartphones'),
('Roupas Masculinas'),
('Roupas Femininas'),
('Decoração para Casa'),
('Literatura'),
('Esportes e Fitness'),
('Jogos de Tabuleiro'),
('Ferramentas e Construção'),
('Beleza e Cuidados Pessoais'),
('Peças e Acessórios Automotivos'),
('Brinquedos e Jogos'),
('Alimentos e Bebidas'),
('Móveis e Decoração'),
('Artesanato e Hobbies'),
('Eletrônicos de Consumo'),
('Jardinagem e Plantas'),
('Instrumentos Musicais'),
('Saúde e Bem-Estar'),
('Suprimentos para Animais'),
('Viagens e Turismo'),
('Roupas Infantis'),
('Eletrodomésticos'),
('Telefonia Celular'),
('Eletroportáteis'),
('Computadores e Tablets'),
('Material de Escritório'),
('Áudio e Vídeo'),
('Fotografia e Filmagem'),
('Produtos Sustentáveis'),
('Acessórios de Moda'),
('Eletrônicos para Casa'),
('Perfumaria e Cosméticos'),
('Moda Íntima e Lingerie'),
('Calçados'),
('Bolsas e Acessórios'),
('Relógios'),
('Artigos para Festas'),
('Suprimentos para Escritório'),
('Material Escolar'),
('Artigos de Papelaria'),
('Utensílios de Cozinha'),
('Lazer e Entretenimento'),
('Ferramentas Manuais'),
('Equipamentos de Segurança'),
('Equipamentos de Limpeza'),
('Roupas Esportivas');


INSERT INTO tb_suppliers (name) VALUES
('ABC Electronics'),
('Smith & Co.'),
('Johnson Manufacturing'),
('Miller Suppliers'),
('Brown Distributors'),
('Davis Tech'),
('Wilson Supplies'),
('Moore Enterprises'),
('Taylor Electronics'),
('Anderson Distributors'),
('Thomas Manufacturing'),
('Jackson Tech'),
('White & Sons'),
('Harris Supplies'),
('Martin Enterprises'),
('Thompson Electronics'),
('Garcia Distributors'),
('Martinez Suppliers'),
('Robinson Manufacturing'),
('Clark Tech'),
('Rodriguez Electronics'),
('Lewis & Co.'),
('Lee Distributors'),
('Walker Suppliers'),
('Hall Manufacturing'),
('Allen Tech'),
('Young Supplies'),
('Hernandez Enterprises'),
('King Electronics'),
('Wright Distributors'),
('Lopez Suppliers'),
('Hill Manufacturing'),
('Scott Tech'),
('Green & Co.'),
('Adams Supplies'),
('Baker Enterprises'),
('Nelson Electronics'),
('Carter Distributors'),
('Mitchell Suppliers'),
('Perez Manufacturing'),
('Roberts Tech'),
('Turner Electronics'),
('Phillips Distributors'),
('Campbell Suppliers'),
('Parker Enterprises'),
('Evans Manufacturing'),
('Edwards Tech'),
('Collins Electronics'),
('Stewart Distributors'),
('Sanchez Suppliers');


INSERT INTO tb_products (name, price, quantity, description, category_id, supplier_id)
VALUES
('Smartphone Samsung Galaxy S21', 999.99, 100, 'High-end smartphone with advanced features.', 1, 1),
('Laptop Dell XPS 15', 1499.99, 50, 'Powerful laptop with a high-resolution display.', 2, 2),
('Smart TV LG OLED55C1', 1999.99, 30, '55-inch OLED TV with stunning picture quality.', 3, 3),
('Apple iPad Pro 12.9-inch', 1099.99, 40, 'Large-screen tablet with powerful performance.', 4, 4),
('Sony PlayStation 5', 499.99, 20, 'Next-gen gaming console with high-fidelity graphics.', 5, 5),
('Bose Noise Cancelling Headphones 700', 379.99, 60, 'Premium headphones with excellent noise cancellation.', 6, 6),
('Canon EOS R5 Mirrorless Camera', 3899.99, 15, 'High-resolution mirrorless camera with advanced features.', 7, 7),
('KitchenAid Stand Mixer', 299.99, 80, 'Powerful stand mixer for baking and cooking.', 8, 8),
('Nespresso VertuoPlus Coffee Maker', 179.99, 90, 'Single-serve coffee maker with a sleek design.', 9, 9),
('Fitbit Charge 5 Fitness Tracker', 179.95, 70, 'Advanced fitness tracker with heart rate monitoring and GPS.', 10, 10),
('Dyson V11 Cordless Vacuum Cleaner', 599.99, 25, 'Powerful cordless vacuum cleaner for home cleaning.', 11, 11),
('Instant Pot Duo 7-in-1 Pressure Cooker', 79.95, 85, 'Multi-functional pressure cooker for quick and easy cooking.', 12, 12),
('LEGO Star Wars Millennium Falcon', 159.99, 45, 'Iconic Star Wars spaceship LEGO set for fans.', 13, 13),
('Samsung 49-Inch Odyssey G9 Gaming Monitor', 1499.99, 35, 'Ultra-wide gaming monitor with high refresh rate.', 14, 14),
('Yeti Tundra 45 Cooler', 299.99, 55, 'High-performance cooler for outdoor adventures.', 15, 15),
('Cuisinart Air Fryer Toaster Oven', 199.95, 75, 'Multi-functional kitchen appliance for air frying and toasting.', 16, 16),
('Amazon Kindle Paperwhite', 129.99, 65, 'Waterproof e-reader with a high-resolution display.', 17, 17),
('DJI Mavic Air 2 Drone', 799.00, 10, 'Compact drone with advanced camera capabilities.', 18, 18),
('Weber Spirit II E-310 Gas Grill', 479.00, 20, 'High-quality gas grill for outdoor cooking.', 19, 19),
('Nintendo Switch Console', 299.99, 30, 'Versatile gaming console for gaming on-the-go.', 20, 20),
('Vitamix 5200 Blender', 449.95, 40, 'Powerful blender for making smoothies and soups.', 21, 21),
('Breville Barista Express Espresso Machine', 699.95, 15, 'Semi-automatic espresso machine for coffee enthusiasts.', 22, 22),
('Garmin Fenix 6 Pro Smartwatch', 699.99, 50, 'Premium GPS smartwatch for outdoor activities.', 23, 23),
('Microsoft Surface Laptop 4', 999.99, 25, 'Sleek and powerful laptop with a touchscreen display.', 24, 24),
('GoPro HERO9 Black Action Camera', 449.99, 30, 'High-quality action camera for capturing adventures.', 25, 25),
('Roku Ultra Streaming Media Player', 99.99, 60, 'Feature-rich streaming media player for accessing entertainment.', 26, 26),
('Crock-Pot 6-Quart Slow Cooker', 49.99, 70, 'Simple and convenient slow cooker for delicious meals.', 27, 27),
('Samsung Galaxy Watch 4', 249.99, 45, 'Stylish and functional smartwatch with health tracking features.', 28, 28),
('LG Gram 17 Laptop', 1299.99, 20, 'Ultra-lightweight and portable laptop with a large display.', 29, 29),
('Anker Soundcore Liberty Air 2 Pro', 129.99, 80, 'True wireless earbuds with active noise cancellation.', 30, 30),
('Nintendo Switch Pro Controller', 69.99, 55, 'Official controller for Nintendo Switch gaming console.', 31, 31),
('Samsung Galaxy Buds Pro', 199.99, 40, 'Premium true wireless earbuds with intelligent ANC.', 32, 32),
('Sony WH-1000XM4 Wireless Headphones', 349.99, 50, 'Industry-leading noise-canceling headphones with premium sound.', 33, 33),
('Fujifilm X-T4 Mirrorless Camera', 1699.95, 15, 'Advanced mirrorless camera with 26.1MP sensor and 4K video.', 34, 34),
('Razer BlackWidow Elite Mechanical Keyboard', 169.99, 30, 'High-performance mechanical keyboard for gaming and typing.', 35, 35),
('JBL Flip 5 Portable Bluetooth Speaker', 119.95, 65, 'Compact and waterproof portable speaker for on-the-go music.', 36, 36),
('Fitbit Versa 3 Smartwatch', 229.95, 40, 'Health and fitness smartwatch with built-in GPS and heart rate monitor.', 37, 37),
('Bose SoundLink Revolve+ Bluetooth Speaker', 299.00, 25, '360-degree portable Bluetooth speaker with deep, loud, and immersive sound.', 38, 38),
('Nikon D850 DSLR Camera', 2996.95, 10, 'Professional-grade DSLR camera with a high-resolution sensor.', 39, 39),
('LG CX 55-Inch OLED 4K TV', 1596.99, 20, 'Cinematic OLED TV with AI ThinQ and Dolby Vision IQ.', 40, 40),
('Apple AirPods Pro', 249.00, 55, 'Premium true wireless earbuds with active noise cancellation.', 41, 41),
('HP Pavilion 27-Inch QHD Monitor', 349.99, 30, '27-inch QHD monitor with an ultra-slim design and built-in speakers.', 42, 42),
('Bose QuietComfort 35 II Wireless Headphones', 299.00, 50, 'Wireless noise-canceling headphones with Alexa voice control.', 43, 43),
('Dyson Supersonic Hair Dryer', 399.99, 25, 'High-speed hair dryer engineered for multiple hair types.', 44, 44),
('Canon EF 24-70mm f/2.8L II USM Lens', 1899.00, 15, 'Professional zoom lens with a fast aperture for versatile shooting.', 45, 45);


INSERT INTO tb_products (name, price, quantity, description, category_id, supplier_id, created_at, updated_at)
VALUES 
  ('Smartphone', 999.99, 50, 'High-end smartphone', 1, 1, '2022-01-01 10:00:00', '2022-01-01 10:30:00'),
  ('Laptop', 1499.99, 20, 'Powerful laptop', 1, 2, '2022-01-02 11:00:00', '2022-01-02 11:45:00'),
  ('Headphones', 99.99, 100, 'Wireless headphones', 1, 3, '2022-01-03 12:00:00', '2022-01-03 12:20:00'),
  ('Smartwatch', 199.99, 30, 'Fitness tracker', 1, 4, '2022-01-04 13:00:00', '2022-01-04 13:15:00');
